name: Ubuntu CI (Build only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Directory
      run: ls -l -a
    - name: Build GLVM with make
      run: make -f MakefileLin
